language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
  - composer self-update
  - phpenv config-add travis.php.ini

install:
  - composer install

script: phpunit --testsuite="Project Unit Tests"
