language: php

php:
    - 5.4
    - 5.5
    - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get install ant-contrib
  - composer self-update
  - phpenv config-add travis.php.ini

#install:
#  - composer install

#script: phpunit --testsuite="Project Unit Tests"
script: ant -f build_config/build.xml unit-tests code-standards
